### ISSUE TITLE
Photran indexer error 

### ISSUE THREAD

**Issue by rsdunlapiv** [cupid-ide/cupid#39]
This error occurs when parsing NEMS

!ENTRY org.eclipse.core.jobs 4 2 2016-08-18 20:27:59.360
!MESSAGE An internal error occurred during: "Photran indexer".
!STACK 0
java.lang.NullPointerException
	at org.eclipse.photran.internal.core.analysis.binding.SubprogramTypeCollector.updateDefinitionWithSubParameters(SubprogramTypeCollector.java:71)
	at org.eclipse.photran.internal.core.analysis.binding.SubprogramTypeCollector.visitASTSubroutineStmtNode(SubprogramTypeCollector.java:46)
	at org.eclipse.photran.internal.core.parser.ASTSubroutineStmtNode.accept(ASTSubroutineStmtNode.java:95)
	at org.eclipse.photran.internal.core.parser.ASTVisitor.traverseChildren(ASTVisitor.java:21)
	at org.eclipse.photran.internal.core.parser.ASTVisitor.visitASTSubroutineSubprogramNode(ASTVisitor.java:371)
	at org.eclipse.photran.internal.core.parser.ASTSubroutineSubprogramNode.accept(ASTSubroutineSubprogramNode.java:100)
	at org.eclipse.photran.internal.core.parser.ASTVisitor.traverseChildren(ASTVisitor.java:21)
	at org.eclipse.photran.internal.core.parser.ASTVisitor.visitASTListNode(ASTVisitor.java:26)
	at org.eclipse.photran.internal.core.parser.ASTListNode.accept(ASTListNode.java:131)
	at org.eclipse.photran.internal.core.parser.ASTVisitor.traverseChildren(ASTVisitor.java:21)
	at org.eclipse.photran.internal.core.parser.ASTVisitor.visitASTExecutableProgramNode(ASTVisitor.java:175)
	at org.eclipse.photran.internal.core.parser.ASTExecutableProgramNode.accept(ASTExecutableProgramNode.java:61)
	at org.eclipse.photran.internal.core.FortranAST.accept(FortranAST.java:53)
	at org.eclipse.photran.internal.core.analysis.binding.Binder.bind(Binder.java:63)
	at org.eclipse.photran.internal.core.vpg.PhotranVPGWriter.populateVPG(PhotranVPGWriter.java:582)
	at org.eclipse.photran.internal.core.vpg.PhotranVPGWriter.populateVPG(PhotranVPGWriter.java:1)
	at org.eclipse.photran.internal.core.vpg.VPGWriter.computeEdgesAndAnnotations(VPGWriter.java:63)
	at org.eclipse.photran.internal.core.vpg.ASTRepository.acquireTransientAST(ASTRepository.java:87)
	at org.eclipse.photran.internal.core.vpg.VPG.forceRecomputationOfEdgesAndAnnotations(VPG.java:405)
	at org.eclipse.photran.internal.core.vpg.eclipse.EclipseVPG.indexIfNotUpToDate(EclipseVPG.java:471)
	at org.eclipse.photran.internal.core.vpg.eclipse.EclipseVPG$WorkspaceSyncResourceVisitor.index(EclipseVPG.java:266)
	at org.eclipse.photran.internal.core.vpg.eclipse.EclipseVPG.ensureVPGIsUpToDate(EclipseVPG.java:182)
	at org.eclipse.photran.internal.core.vpg.eclipse.EclipseVPG$VPGInitialWorkspaceSyncJob.runInWorkspace(EclipseVPG.java:161)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

**Comment by rsdunlapiv** [comment]
Submitted a patch to Photran and it was accepted and merged.
https://git.eclipse.org/r/#/c/79390/
